service: github-branch-bot

provider:
  name: aws
  region: eu-west-2
  runtime: go1.x
  timeout: 60

package:
  individually: true

functions:
  github-branch-bot:
    handler: bin/github-branch-bot
    environment:
      GITHUB_BASE_URL: ""
      GITHUB_TOKEN: ""
      GITHUB_ORGANISATION: ""
      BASE_BRANCH: ""
      HEAD_BRANCH_PREFIX: ""
      WEBHOOK_URL: ""
    events:
      - schedule: cron(0 0 ? * MON-FRI *)
    package:
      artifact: bin/github-branch-bot.zip
  github-branch-check:
    handler: bin/github-branch-check
    environment:
      GITHUB_BASE_URL: ""
      GITHUB_TOKEN: ""
      GITHUB_ORGANISATION: ""
      BASE_BRANCH: ""
      HEAD_BRANCH_PREFIX: ""
      SLACK_COMMAND_TOKEN: ""
    events:
      - http:
          path: /
          method: get
          async: true
          request:
           parameters:
            querystrings:
              token: true
              response_url: true
    package:
      artifact: bin/github-branch-check.zip
