service: github-branch-bot

provider:
  name: aws
  region: eu-west-2
  runtime: go1.x
  timeout: 60

functions:
  github-branch-bot:
    handler: bin/github-branch-bot
    environment:
      GITHUB_BASE_URL: ""
      GITHUB_TOKEN: ""
      GITHUB_ORGANISATION: ""
      BASE_BRANCH: ""
      HEAD_BRANCH_PREFIX: ""
      WEBHOOK_URL: ""
    events:
      - schedule: cron(0 0 ? * * *)
      - http:
          path: /
          method: get

package:
  artifact: bin/github-branch-bot.zip